// Automatically generated by flapigen
package com.example.rustapplication.lib;
import androidx.annotation.NonNull;

public final class Exercise {

    public Exercise(@NonNull String name, @NonNull String initial_date) {
        mNativeObj = init(name, initial_date);
    }
    private static native long init(@NonNull String name, @NonNull String initial_date);

    public Exercise(@NonNull String s) {
        mNativeObj = init(s);
    }
    private static native long init(@NonNull String s);

    public final void addEntry(@NonNull Entry entry) {
        long a0 = entry.mNativeObj;
        entry.mNativeObj = 0;

        do_addEntry(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(entry);
    }
    private static native void do_addEntry(long self, long entry);

    public final @NonNull String getName() {
        String ret = do_getName(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getName(long self);

    public final long getInitialWeight() {
        long ret = do_getInitialWeight(mNativeObj);

        return ret;
    }
    private static native long do_getInitialWeight(long self);

    public final long getInitialReps() {
        long ret = do_getInitialReps(mNativeObj);

        return ret;
    }
    private static native long do_getInitialReps(long self);

    public final long getInitialSets() {
        long ret = do_getInitialSets(mNativeObj);

        return ret;
    }
    private static native long do_getInitialSets(long self);

    public final @NonNull String getInitialDate() {
        String ret = do_getInitialDate(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getInitialDate(long self);

    public final long getMaxWeight() {
        long ret = do_getMaxWeight(mNativeObj);

        return ret;
    }
    private static native long do_getMaxWeight(long self);

    public final long getMaxReps() {
        long ret = do_getMaxReps(mNativeObj);

        return ret;
    }
    private static native long do_getMaxReps(long self);

    public final long getMaxSets() {
        long ret = do_getMaxSets(mNativeObj);

        return ret;
    }
    private static native long do_getMaxSets(long self);

    public final @NonNull String getMaxDate() {
        String ret = do_getMaxDate(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getMaxDate(long self);

    public final @NonNull String getLastDate() {
        String ret = do_getLastDate(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getLastDate(long self);

    public final long getEntryCount() {
        long ret = do_getEntryCount(mNativeObj);

        return ret;
    }
    private static native long do_getEntryCount(long self);

    public final @NonNull String getLogString() {
        String ret = do_getLogString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getLogString(long self);

    public final @NonNull String toString() {
        String ret = do_toString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_toString(long self);

    public final @NonNull String displayToString() {
        String ret = do_displayToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_displayToString(long self);

    public final @NonNull String noteToString() {
        String ret = do_noteToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_noteToString(long self);

    public final @NonNull String prettyToString() {
        String ret = do_prettyToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_prettyToString(long self);

    public final @NonNull String maxToString() {
        String ret = do_maxToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_maxToString(long self);

    public final @NonNull String initialToString() {
        String ret = do_initialToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_initialToString(long self);

    public final @NonNull String resultToString() {
        String ret = do_resultToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_resultToString(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Exercise(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}