// Automatically generated by flapigen
package com.example.rustapplication.lib;
import androidx.annotation.NonNull;

public final class Exercise {

    public Exercise(@NonNull String name, long weight, long reps, long sets) {
        mNativeObj = init(name, weight, reps, sets);
    }
    private static native long init(@NonNull String name, long weight, long reps, long sets);

    public final @NonNull String toString() {
        String ret = do_toString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_toString(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Exercise(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}