// Automatically generated by flapigen
package com.example.rustapplication.lib;
import androidx.annotation.NonNull;

public final class History {

    public History(@NonNull String start_date, long exercise_count) {
        mNativeObj = init(start_date, exercise_count);
    }
    private static native long init(@NonNull String start_date, long exercise_count);

    public History(@NonNull String s) {
        mNativeObj = init(s);
    }
    private static native long init(@NonNull String s);

    public final void addExercise(@NonNull Exercise exercise) {
        long a0 = exercise.mNativeObj;
        exercise.mNativeObj = 0;

        do_addExercise(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(exercise);
    }
    private static native void do_addExercise(long self, long exercise);

    public final void mergeHistory(@NonNull History history) {
        long a0 = history.mNativeObj;
        history.mNativeObj = 0;

        do_mergeHistory(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(history);
    }
    private static native void do_mergeHistory(long self, long history);

    public final long getExerciseCount() {
        long ret = do_getExerciseCount(mNativeObj);

        return ret;
    }
    private static native long do_getExerciseCount(long self);

    public final @NonNull String getStartDate() {
        String ret = do_getStartDate(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getStartDate(long self);

    public final @NonNull String getLastDate() {
        String ret = do_getLastDate(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getLastDate(long self);

    public final @NonNull String getLogString() {
        String ret = do_getLogString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_getLogString(long self);

    public final @NonNull String toString() {
        String ret = do_toString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_toString(long self);

    public final @NonNull String prettyToString() {
        String ret = do_prettyToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_prettyToString(long self);

    public final @NonNull String displayToString() {
        String ret = do_displayToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_displayToString(long self);

    public final @NonNull String exerciseToString() {
        String ret = do_exerciseToString(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_exerciseToString(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ History(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}